// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetopiaWebApi.Models;

#nullable disable

namespace PetopiaWebApi.Migrations
{
    [DbContext(typeof(PetopiaDbContext))]
    [Migration("20260707164829_InitialCreatePostgres")]
    partial class InitialCreatePostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetopiaWebApi.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.HasKey("AdminId")
                        .HasName("PK__admin__43AA41416FA8F5DF");

                    b.HasIndex(new[] { "Email" }, "UQ__admin__AB6E6164AA1BBB67")
                        .IsUnique();

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("PetopiaWebApi.Models.AdoptionStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<int>("PetId")
                        .HasColumnType("integer")
                        .HasColumnName("pet_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("StatusId")
                        .HasName("PK__adoption__3683B53114E6A628");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("adoption_status", (string)null);
                });

            modelBuilder.Entity("PetopiaWebApi.Models.Breed", b =>
                {
                    b.Property<int>("BreedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("breed_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BreedId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("BreedId")
                        .HasName("PK__breed__9C02143553FA916A");

                    b.HasIndex("CategoryId");

                    b.ToTable("breed", (string)null);
                });

            modelBuilder.Entity("PetopiaWebApi.Models.PetCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("PK__pet_cate__D54EE9B4CF21D854");

                    b.HasIndex(new[] { "Name" }, "UQ__pet_cate__72E12F1BF2955269")
                        .IsUnique();

                    b.ToTable("pet_category", (string)null);
                });

            modelBuilder.Entity("PetopiaWebApi.Models.PetImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_path");

                    b.Property<int>("PetId")
                        .HasColumnType("integer")
                        .HasColumnName("pet_id");

                    b.HasKey("ImageId")
                        .HasName("PK__pet_imag__DC9AC9554D3966CD");

                    b.HasIndex("PetId");

                    b.ToTable("pet_images", (string)null);
                });

            modelBuilder.Entity("PetopiaWebApi.Models.PetProfile", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pet_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PetId"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<int>("BreedId")
                        .HasColumnType("integer")
                        .HasColumnName("breed_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<bool?>("GoodWithKids")
                        .HasColumnType("boolean")
                        .HasColumnName("good_with_kids");

                    b.Property<bool?>("GoodWithPets")
                        .HasColumnType("boolean")
                        .HasColumnName("good_with_pets");

                    b.Property<string>("Health")
                        .HasColumnType("text")
                        .HasColumnName("health");

                    b.Property<bool?>("HouseTrained")
                        .HasColumnType("boolean")
                        .HasColumnName("house_trained");

                    b.Property<string>("IsRegisteredWithGovt")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("no")
                        .HasColumnName("isRegisteredWithGovt");

                    b.Property<decimal?>("MonthlyExpenses")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monthly_expenses");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Needs")
                        .HasColumnType("text")
                        .HasColumnName("needs");

                    b.Property<string>("Personality")
                        .HasColumnType("text")
                        .HasColumnName("personality");

                    b.Property<string>("Size")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("size");

                    b.Property<bool?>("Spayed")
                        .HasColumnType("boolean")
                        .HasColumnName("spayed");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool?>("Vaccinated")
                        .HasColumnType("boolean")
                        .HasColumnName("vaccinated");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weight");

                    b.HasKey("PetId")
                        .HasName("PK__pet_prof__390CC5FE6B06AC88");

                    b.HasIndex("BreedId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("pet_profile", (string)null);
                });

            modelBuilder.Entity("PetopiaWebApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_no");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_role");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F1C04A088");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E616403F5D9A0")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PetopiaWebApi.Models.AdoptionStatus", b =>
                {
                    b.HasOne("PetopiaWebApi.Models.PetProfile", "Pet")
                        .WithMany("AdoptionStatuses")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__adoption___pet_i__5629CD9C");

                    b.HasOne("PetopiaWebApi.Models.User", "User")
                        .WithMany("AdoptionStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__adoption___user___571DF1D5");

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetopiaWebApi.Models.Breed", b =>
                {
                    b.HasOne("PetopiaWebApi.Models.PetCategory", "Category")
                        .WithMany("Breeds")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__breed__category___3F466844");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PetopiaWebApi.Models.PetImage", b =>
                {
                    b.HasOne("PetopiaWebApi.Models.PetProfile", "Pet")
                        .WithMany("PetImages")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__pet_image__pet_i__52593CB8");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetopiaWebApi.Models.PetProfile", b =>
                {
                    b.HasOne("PetopiaWebApi.Models.Breed", "Breed")
                        .WithMany("PetProfiles")
                        .HasForeignKey("BreedId")
                        .IsRequired()
                        .HasConstraintName("FK__pet_profi__breed__4E88ABD4");

                    b.HasOne("PetopiaWebApi.Models.PetCategory", "Category")
                        .WithMany("PetProfiles")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__pet_profi__categ__4D94879B");

                    b.HasOne("PetopiaWebApi.Models.User", "User")
                        .WithMany("PetProfiles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__pet_profi__user___4F7CD00D");

                    b.Navigation("Breed");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetopiaWebApi.Models.Breed", b =>
                {
                    b.Navigation("PetProfiles");
                });

            modelBuilder.Entity("PetopiaWebApi.Models.PetCategory", b =>
                {
                    b.Navigation("Breeds");

                    b.Navigation("PetProfiles");
                });

            modelBuilder.Entity("PetopiaWebApi.Models.PetProfile", b =>
                {
                    b.Navigation("AdoptionStatuses");

                    b.Navigation("PetImages");
                });

            modelBuilder.Entity("PetopiaWebApi.Models.User", b =>
                {
                    b.Navigation("AdoptionStatuses");

                    b.Navigation("PetProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
